# File .github/workflows/publish-snapshot.yml

# Runs on push to branches (/feature/hotfix/)
# this workflow publishes SNAPSHOT maven artifact

name: publish SNAPSHOT
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'hotfix/**'
  workflow_dispatch:

jobs:
  validate: # SERVICE LEVEL - CHECK AND SHARE VARIABLES
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.repository.outputs.environment }}
      repository_type: ${{ steps.repository.outputs.repository_type }}
    steps:
      - uses: actions/checkout@v4
      - id: repository
        uses: ./.github/actions/common/validate
        with:
          type: 'snapshot'

  publish:
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build and Publish
        uses: ./.github/actions/publish/snapshot/library