# File .github/workflows/publish-snapshot.yml

# Runs on push to branches (/feature/hotfix/)
# this workflow publishes SNAPSHOT maven artifact

name: publish SNAPSHOT
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'hotfix/**'
  workflow_dispatch:

jobs:
  validate: # SERVICE LEVEL - CHECK AND SHARE VARIABLES
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.repository.outputs.environment }}
      repository_type: ${{ steps.repository.outputs.repository_type }}
    steps:
      - uses: actions/checkout@v4
      - id: repository
        uses: ./.github/actions/common/validate
        with:
          type: 'snapshot'

  publish:
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write     # Crucial for pushing package
      attestations: write # Optional, for supply-chain security
      id-token: write     # Optional, for OIDC
    outputs:
      image-name: ${{ steps.image.outputs.image-name }}
      image-tags: ${{ steps.image.outputs.image-tags }}
      image-tag:  ${{ steps.image.outputs.image-tag }}
      image-digest: ${{ steps.image.outputs.image-digest }}
    steps:
      - uses: actions/checkout@v4
      - id: image
        uses: ./.github/actions/publish/snapshot/docker

  deploy:
    environment: ${{ needs.validate.outputs.environment }}
    needs:
      - validate
      - publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy/k8s
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          verify_access: no
          helm_files: ./.github/k8s/values.yml
          helm_properties: |
            service.environment=dev
            service.image.name=nginx
            service.image.tag=1.27-alpine