# File .github/workflows/publish-release.yml

# Runs on creating a new release tag (when this release marked as published)
# this workflow publishes maven artifact and does increment the next SNAPSHOT version

name: publish RELEASE
on:
  release:
    types:
      - published

jobs:
  repository:
    if: ${{ !startsWith(github.repository, 'madbuilds/template-') }}
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.validate.outputs.type }}
      language: ${{ steps.validate.outputs.language }}
    env:
      REPOSITORY_TYPE:     $(jq -r '.repository.custom_properties.type     | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
      REPOSITORY_LANGUAGE: $(jq -r '.repository.custom_properties.language | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
    steps:
      - name: validate repository type
        id: validate
        run: |
          echo "repository type:     ${{ env.REPOSITORY_TYPE }}"
          echo "repository language: ${{ env.REPOSITORY_LANGUAGE }}"
          echo "type=${{ env.REPOSITORY_TYPE }}" >> $GITHUB_OUTPUT
          echo "language=${{ env.REPOSITORY_LANGUAGE }}" >> $GITHUB_OUTPUT

  publish-service:
    needs: repository
    if: needs.repository.outputs.type == 'service'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write # Crucial for pushing package
      attestations: write # Optional, for supply-chain security
      id-token: write # Optional, for OIDC
    steps:
      - uses: actions/checkout@v4