# File .github/workflows/publish-release.yml

# Runs on creating a new release tag (when this release marked as published),
# this workflow publishes artifact and does increment the next SNAPSHOT version

name: publish RELEASE
on:
  release:
    types:
      - published

jobs:
  repository:
    if: ${{ !startsWith(github.repository, 'madbuilds/template-') }}
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.validate.outputs.type }}
      language: ${{ steps.validate.outputs.language }}
      environment: ${{ steps.validate.outputs.environment }}
    env:
      REPOSITORY_TYPE:     $(jq -r '.repository.custom_properties.type     | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
      REPOSITORY_LANGUAGE: $(jq -r '.repository.custom_properties.language | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
    steps:
      - name: validate repository type
        id: validate
        run: |
          echo "repository type:     ${{ env.REPOSITORY_TYPE }}"
          echo "repository language: ${{ env.REPOSITORY_LANGUAGE }}"
          echo "type=${{ env.REPOSITORY_TYPE }}" >> $GITHUB_OUTPUT
          echo "language=${{ env.REPOSITORY_LANGUAGE }}" >> $GITHUB_OUTPUT
          echo "environment=PRODUCTION" >> $GITHUB_OUTPUT

  publish-service:
    needs: repository
    if: needs.repository.outputs.type == 'service'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write # Crucial for pushing package
      attestations: write # Optional, for supply-chain security
      id-token: write # Optional, for OIDC
    steps:
      - uses: actions/checkout@v4

      - name: Build and Publish Docker Image to GHCR
        id: publish
        uses: ./.github/actions/publish/release/docker

      - name: Output Image Digest and Tags
        run: |
          echo "Image Digest: ${{ steps.publish.outputs.image-digest }}"
          echo "Image Tags: ${{ steps.publish.outputs.image-tags }}"
          echo "test: ${{ secrets.SOME_SECRET }}"

  deploy:
    environment: ${{ needs.repository.outputs.environment }}
    needs:
      - repository
      - publish-service
    runs-on: ubuntu-latest
    steps:
      - name: Output
        id: output
        run: |
          echo "test: ${{ secrets.SOME_ENV_SECRET }}"
          echo "tags: ${{ needs.build-and-publish.outputs.tags }}"
          echo "digest: ${{ needs.build-and-publish.outputs.digest }}"