# File .github/workflows/publish-snapshot.yml

# Runs on push to branches (/feature/hotfix/)
# this workflow publishes SNAPSHOT maven artifact

name: publish SNAPSHOT
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'hotfix/**'
  workflow_dispatch:

env:
  REPOSITORY_TYPE: $(jq -r '.repository.custom_properties.type     | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTIONS_NAME: github-actions[bot]
  GITHUB_ACTIONS_MAIL: github-actions[bot]@users.noreply.github.com

jobs:
  validate:
    if: ${{ !startsWith(github.repository, 'madbuilds/template-') }}
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.is_required.outputs.run }}
      type: ${{ steps.repository.outputs.type }}

    steps:
      - uses: actions/checkout@v4
      - name: is publish required
        id: is_required
        run: |
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
          if [[ "$COMMIT_AUTHOR" == "${{ env.GITHUB_ACTIONS_NAME }}" ]]; then
            echo "run=false" >> $GITHUB_OUTPUT
            echo "SKIP: SNAPSHOT publication not required"
          else
            echo "run=true" >> $GITHUB_OUTPUT
            echo "PROCESS: SNAPSHOT publication required"
          fi

      - name: repository type
        id: repository
        run: |
          echo "repository type: ${{ env.REPOSITORY_TYPE }}"
          echo "type=${{ env.REPOSITORY_TYPE }}" >> $GITHUB_OUTPUT

  publish-library:
    needs: validate
    if: needs.validate.outputs.run == 'true' && needs.validate.outputs.type == 'library'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: build deploy
        uses: ./.github/actions/publish/snapshot/library

  publish-service:
    needs: validate
    if: needs.validate.outputs.run == 'true' && needs.validate.outputs.type == 'service'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4