# File .github/workflows/publish-release.yml

# Runs on creating a new release tag (when this release marked as published)
# this workflow publishes maven artifact and does increment the next SNAPSHOT version

name: publish RELEASE
on:
  release:
    types:
      - published

env:
  REPOSITORY_TYPE: $(jq -r '.repository.custom_properties.type     | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTIONS_NAME: github-actions[bot]

jobs:
  validate:
    if: ${{ !startsWith(github.repository, 'madbuilds/template-') }}
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.repository.outputs.type }}
    steps:
      - name: repository type
        id: repository
        run: |
          echo "repository type: ${{ env.REPOSITORY_TYPE }}"
          echo "type=${{ env.REPOSITORY_TYPE }}" >> $GITHUB_OUTPUT

  publish-library:
    needs: validate
    if: needs.validate.outputs.type == 'library'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: build deploy
        uses: ./.github/actions/publish/release/library

  publish-service:
    needs: validate
    if: needs.validate.outputs.type == 'service'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4