# File .github/workflows/repository-update.yml
# DESCRIPTION: repos cannot use ORGANIZATION's secrets/vars on the free organization plan
#              as is a workaround, this action sync's repo secrets with a list of repositories
# ${secrets.MADBUILDS_TEMPLATE_SECRETS_SYNC_PAT} - required to have "repo" access for USER_PAT token

on:
  workflow_dispatch:

env:
  REPOSITORIES: >
    telegram-donation-ui
    app-logging
    pritunl
    some-service
    sbot

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.repositories }}
    steps:
      - id: matrix
        run: |
          while IFS= read -r repository: do
            [[ -z "$repository" ]] && continue
            if [[ -z "$json" ]]; then
              json="\"$repository\""
            else
              json="$json,\"$repository\""
            fi
          done <<< "${{ env.REPOSITORIES }}"
          echo "repositories=[ ${json} ]" >> $GITHUB_OUTPUT

  update:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: update variables
        uses: ./.github/actions/common/template/update-secrets
        with:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}
          repositories: ${{ matrix.repository }}
          variables: |
            TEST_VAR="Set from composite action"

      - name: update prod secrets
        uses: ./.github/actions/common/template/update-secrets
        with:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}
          repositories: ${{ matrix.repository }}
          environment: PRODUCTION
          secrets: |
            MADBUILDS_SSH_PRIVATE_HOST=${{ secrets.MADBUILDS_SSH_DEV_PRIVATE_HOST }}
            MADBUILDS_SSH_PRIVATE_PORT=${{ secrets.MADBUILDS_SSH_DEV_PRIVATE_PORT }}
            MADBUILDS_SSH_PRIVATE_USER=${{ secrets.MADBUILDS_SSH_DEV_PRIVATE_USER }}
          key: MADBUILDS_SSH_PRIVATE_KEY
          value: ${{ secrets.MADBUILDS_SSH_DEV_PRIVATE_KEY }}

      - name: update test secrets
        uses: ./.github/actions/common/template/update-secrets
        with:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}
          repositories: ${{ matrix.repository }}
          environment: TEST
          secrets: |
            MADBUILDS_SSH_PRIVATE_HOST=${{ secrets.MADBUILDS_SSH_DEV_PRIVATE_HOST }}
            MADBUILDS_SSH_PRIVATE_PORT=${{ secrets.MADBUILDS_SSH_DEV_PRIVATE_PORT }}
            MADBUILDS_SSH_PRIVATE_USER=${{ secrets.MADBUILDS_SSH_DEV_PRIVATE_USER }}
          key: MADBUILDS_SSH_PRIVATE_KEY
          value: ${{ secrets.MADBUILDS_SSH_DEV_PRIVATE_KEY }}

      - name: update other secrets
        uses: ./.github/actions/common/template/update-secrets
        with:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}
          repositories: ${{ matrix.repository }}
          secrets: |
            MADBUILDS_SYNCAPP_APP_ID=${{ secrets.MADBUILDS_SYNCAPP_APP_ID }}
            MADBUILDS_SYNCAPP_CLIENT_ID=${{ secrets.MADBUILDS_SYNCAPP_CLIENT_ID }}
            MADBUILDS_SYNCAPP_CLIENT_SECRET=${{ secrets.MADBUILDS_SYNCAPP_CLIENT_SECRET }}
          key: MADBUILDS_SYNCAPP_PRIVATE_KEY
          value: ${{ secrets.MADBUILDS_SYNCAPP_PRIVATE_KEY }}

      - name: init repository
        uses: ./.github/actions/common/template/execute-workflow
        with:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}
          repositories: ${{ matrix.repository }}
          workflow: repository-init.yml

      - name: update branch protection
        uses: ./.github/actions/common/template/protect-branch
        with:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}
          repositories: ${{ matrix.repository }}
          branch: master
